version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8098
    volumes:
      - .:/app
    ports:
      - "8098:8098"
    expose:
      - "8098"  # Expose the port for WebSocket communication
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

